[[plugins]]
repo = 'ghifarit53/tokyonight-vim'


[[plugins]]
repo = 'junegunn/fzf'
build_on = '''
./install -all
'''

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'previm/previm'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'markonm/traces.vim'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'beyondmarc/hlsl.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'justmao945/vim-clang'

[[plugins]]
repo = 'andymass/vim-matchup'
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-jp/syntax-vim-ex'

[[plugins]]
repo = 'Shougo/unite.vim'
[[plugins]]
repo = 'cocopon/vaffle.vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'itchyny/vim-cursorword'

[[plugins]]
repo = 'thinca/vim-quickrun'



# Markdown
[[plugins]]
repo = 'instant-markdown/vim-instant-markdown'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'airblade/vim-gitgutter'

# Rust
[[plugins]]
repo = 'rust-lang/rust.vim'

# Go
[[plugins]]
repo = 'fatih/vim-go'
